export const opencodeGoInfo = {
  name: "OpenCode Go",
  baseUrl: "https://opencode.ai/zen/go/v1",
  // Only models served through the OpenAI-compatible /chat/completions
  // endpoint (see https://opencode.ai/docs/go). Models using /responses or
  // /messages are excluded because they are not callable through the OpenAI SDK.
  modelFilters: [
    "glm-5.3-flash",
    "glm-5.3",
    "glm-5.2",
    "glm-5.1",
    "kimi-k3",
    "kimi-k2.7-code",
    "kimi-k2.6",
    "longcat-2.0",
    "deepseek-v4.1-flash",
    "deepseek-v4-pro",
    "deepseek-v4-flash",
    "deepseek-v4-flash-vision-exp",
    "mimo-v2.6-flash",
    "mimo-v2.6-pro",
    "mimo-v2.5",
    "mimo-v2.5-pro",
    "hy4-preview",
    "hy3",
  ] as string[],
  modelNames: {} as Record<string, string>,
  // Used when the /models endpoint is unavailable.
  fallbackModels: [
    "glm-5.3-flash",
    "glm-5.3",
    "glm-5.2",
    "glm-5.1",
    "kimi-k3",
    "kimi-k2.7-code",
    "kimi-k2.6",
    "longcat-2.0",
    "deepseek-v4.1-flash",
    "deepseek-v4-pro",
    "deepseek-v4-flash",
    "deepseek-v4-flash-vision-exp",
    "mimo-v2.6-flash",
    "mimo-v2.6-pro",
    "mimo-v2.5",
    "mimo-v2.5-pro",
    "hy4-preview",
    "hy3",
  ] as string[],
};
